version: '3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=djdf1605
      - POSTGRES_DB=innowise
  web:
    build: ./innowise_task
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./innowise_task:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
 
volumes:
  postgres_data:
