# Generated by Django 3.1.6 on 2021-02-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
